name: Check Links (Fail Fast)

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args: --verbose --no-progress --cache --max-cache-age 1d --header 'accept=text/html' --user-agent 'curl/7.79.1' './content/**/*'
          fail: true
