name: Daily Vercel Build
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Build Hook
        env:
          TOKEN: ${{ secrets.VERCEL_DEPLOY_DAILY}}
        run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/${TOKEN}
