name: Scheduled Daily Build
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger our build hook on Netlify
        env:
          TOKEN: ${{ secrets.NETLIFY_DEPLOY_DAILY}}
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${TOKEN}
