name: Deploy After CMS Edit

on:
  push:
    branches:
        - main

jobs:
  hit-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get the email of the commit author
      - name: Get Commit Author Email
        id: get-author-email
        run: |
          echo "author_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

      - name: Hit Vercel Deploy Hook
        # user email format is {user.id}+{user.login}@users.noreply.github.com
        if: env.author_email == '103856042+dirtynotsorry-cms@users.noreply.github.com'
        run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/${TOKEN}
