name: Deploy After CMS Edit

on:
  push:
    branches:
        - main

jobs:
  deploy-site-if-cms-edit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get the email of the commit author
      - name: Get Commit Author Email
        id: get-author-email
        run: |
          echo "author_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

      - name: Hit Vercel Deploy Hook
        env:
          TOKEN: ${{ secrets.VERCEL_DEPLOY_DAILY}}
        if: env.author_email == 'admin@dirtynotsorry.com'
        run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/${TOKEN}
